import { describe, expect, it } from "vitest";
import { CNPJ } from "../src/index.js";

describe("CNPJ", () => {
  describe("isValid", () => {
    it("should accept a valid numeric CNPJ with formatting", () => {
      expect(CNPJ.isValid("11.222.333/0001-81")).toBe(true);
    });

    it("should accept a valid numeric CNPJ without formatting", () => {
      expect(CNPJ.isValid("11222333000181")).toBe(true);
    });

    it("should reject an invalid CNPJ", () => {
      expect(CNPJ.isValid("11.222.333/0001-82")).toBe(false);
    });

    it("should reject repeated digits", () => {
      expect(CNPJ.isValid("11.111.111/1111-11")).toBe(false);
    });

    it("should reject CNPJ with incorrect length", () => {
      expect(CNPJ.isValid("1122233300018")).toBe(false);
    });

    it("should reject CNPJ with special characters", () => {
      expect(CNPJ.isValid("11.222.333/@001-81")).toBe(false);
    });

    it("should accept multiple valid numeric CNPJs, including different branch numbers sharing the same root", () => {
      const validCnpjs = [
        "00.777.723/0001-00",
        "00.777.723/1476-23",
        "00.777.723/2476-87",
        "00.777.723/3229-99",
        "00.777.723/4519-69",
        "00.777.723/0751-00",
        "42.755.665/0001-55",
        "42.755.665/7618-65",
        "42.755.665/2428-33",
        "42.755.665/6247-95",
        "42.755.665/7222-90",
        "42.755.665/8166-00",
        "85.333.762/0001-62",
        "85.333.762/1873-00",
        "85.333.762/4083-23",
        "85.333.762/1128-07",
        "85.333.762/2682-11",
        "85.333.762/1336-34",
        "04.769.491/0001-90",
        "57.847.140/0001-17",
        "18.405.334/0001-00",
        "78.598.990/0001-07",
        "98.139.666/0001-20",
        "74.200.778/0001-80",
        "49.941.793/0001-32",
      ];

      for (const cnpj of validCnpjs) {
        expect(CNPJ.isValid(cnpj)).toBe(true);
      }
    });
  });

  describe("normalize", () => {
    it("should remove formatting", () => {
      expect(CNPJ.normalize("11.222.333/0001-81")).toBe("11222333000181");
    });

    it("should return an already normalized CNPJ unchanged", () => {
      expect(CNPJ.normalize("11222333000181")).toBe("11222333000181");
    });
  });

  describe("format", () => {
    it("should format a normalized CNPJ", () => {
      expect(CNPJ.format("11222333000181")).toBe("11.222.333/0001-81");
    });

    it("should keep a formatted CNPJ formatted", () => {
      expect(CNPJ.format("11.222.333/0001-81")).toBe("11.222.333/0001-81");
    });

    it("should return the original value when the length is invalid", () => {
      expect(CNPJ.format("123")).toBe("123");
    });
  });

  describe("alphanumeric", () => {
    it("should accept an alphanumeric CNPJ", () => {
      expect(CNPJ.isValid("12.ABC.345/01DE-35")).toBe(true);
    });

    it("should normalize an alphanumeric CNPJ", () => {
      expect(CNPJ.normalize("12.ABC.345/01DE-35")).toBe("12ABC34501DE35");
    });

    it("should format an alphanumeric CNPJ", () => {
      expect(CNPJ.format("12ABC34501DE35")).toBe("12.ABC.345/01DE-35");
    });

    // Generated with Receita Federal's official simulator:
    // https://servicos.receitafederal.gov.br/servico/cnpj-alfa/simular
    it("should accept alphanumeric CNPJs generated by the official Receita Federal simulator", () => {
      const officialExamples = [
        "HD.D6E.N85/0001-38",
        "P4.W9Z.N4E/0001-47",
        "VJ.AGE.C9J/0001-46",
        "CJ.TLM.0JM/0001-88",
        "CJ.TLM.0JM/JPPZ-15",
        "CJ.TLM.0JM/1RD1-50",
        "CJ.TLM.0JM/HSWB-47",
        "CJ.TLM.0JM/0P56-99",
        "YG.8DJ.YZK/0001-57",
        "YG.8DJ.YZK/6JW7-66",
        "YG.8DJ.YZK/AX68-35",
        "GG.CBW.BAD/0001-94",
        "GG.CBW.BAD/PWRR-99",
        "GG.CBW.BAD/0K1T-41",
        "GG.CBW.BAD/L1YA-78",
        "GG.CBW.BAD/WLR5-06",
      ];

      for (const cnpj of officialExamples) {
        expect(CNPJ.isValid(cnpj)).toBe(true);
      }
    });

    it("should reject an official alphanumeric CNPJ example with a tampered check digit", () => {
      expect(CNPJ.isValid("HD.D6E.N85/0001-39")).toBe(false);
    });
  });
});
